### ISSUE TITLE
Issue with docker compose

### ISSUE THREAD

**Issue by killmasta93** [mawoka-myblock/ClassQuiz#272]
### Which component is affected?

installing

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On a self-hosted instance

### How can the issue be reproduced?

Hi currently im having issue with the docker compose 

  line 89: mapping key "volumes" already defined at line 44

### Describe the bug (with screenshots if possible)

attaching the docker compose

```
version: "3"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - api
    environment:
      REDIS_URL: redis://redis:6379/0?decode_responses=True # don't change
      API_URL: http://api:80 # don't change
  api:
    build: &build_cfg
      context: .
      dockerfile: Dockerfile
    restart: &restart always
    depends_on: &depends
      - db
      - redis

    environment: &env_vars
      ROOT_ADDRESS: "https://quiz.domain.com" # Base-URL (change it)
      DB_URL: "postgresql://postgres:classquiz@db:5432/classquiz" # don't change
      MAIL_ADDRESS: "noticias@domain.com.co" # Email-Address (change it)
      MAIL_PASSWORD: "xxxxxx" # Email-Password (change it)
      MAIL_USERNAME: "email@domain.com.co" # Email-Username (change it)
      MAIL_SERVER: "mail.domain.com.co" # SMTP-Server (change it)
      MAIL_PORT: "587" # SMTP-Port
      SKIP_EMAIL_VERIFICATION: True # Set this to skip sending emails
      MAX_WORKERS: "1" # Very important and don't change it!
      REDIS: "redis://redis:6379/0?decode_responses=True" # don't change
      SECRET_KEY: "f610c6c42d9e2e128c3500175400bc96016c3122eb388e67a454c70c8c5f6e28" # openssl rand -hex 32
      MEILISEARCH_URL: "http://meilisearch:7700" # don't change
      ACCESS_TOKEN_EXPIRE_MINUTES: 30 # don't change
      HCAPTCHA_KEY: "ee81b2a1-acf3-4d20-b2a4-a7ea94c7eba5" # Private hCaptcha key for verification (change it)
STORAGE_BACKEND: "local" # MUST BE EITHER "s3" OR "local"
FREE_STORAGE_LIMIT: "1074000000" # Free storage limit in bytes (default: 1GB)


STORAGE_PATH: "/var/storage"
volumes: # Only needed if you chose the "local" storage-backend
  - ./uploads:/var/storage
redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "classquiz"
      POSTGRES_DB: "classquiz"

    volumes:
      - data:/var/lib/postgresql/data
proxy:
    image: caddy:alpine
    restart: always
    volumes:
      - ./Caddyfile-docker:/etc/caddy/Caddyfile
    ports:
      - "9001:8080" # Adjust the 8000 to your needs

meilisearch:
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meilisearch-data:/data.ms
worker:
    build: *build_cfg
    environment: *env_vars
    restart: *restart
    depends_on: *depends
    command: arq classquiz.worker.WorkerSettings


volumes:
  data:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/quiz/data

  meilisearch-data:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/quiz/melisearchdata
```

### Device

Desktop

### Operating System

linux

### Browser

chrome
