### ISSUE TITLE
Question about hiding the registration 

### ISSUE THREAD

**Issue by farzadha2** [mawoka-myblock/ClassQuiz#273]
Hi
I was wondering if its possible to hide the registration.
As currently we dont users to register only if we allow to is that possible?

Thank you

**Comment by mawoka-myblock** [comment]
Should be possible

**Comment by mawoka-myblock** [comment]
To enable this new feature, do the following:
1. Add `ENV VITE_REGISTRATION_DISABLED=True` to your `frontend/Dockerfile` under all the other `ENV`-keywords and rebuild the container (`docker compose build`)
2. Set the environment-variable `REGISTRATION_DISABLED=True` for the backend

**Comment by killmasta93** [comment]
hi @mawoka-myblock I was trying to follow the guide but cant seem to disable registration 

This is my Docker compose 
```

version: "3"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - api
    networks:
      - rss_default
    environment:
      REDIS_URL: redis://redis:6379/0?decode_responses=True
      API_URL: http://api:80
      ENV_VITE_REGISTRATION_DISABLED: True
  api:
    build: &build_cfg
      context: .
      dockerfile: Dockerfile
    restart: &restart always
    networks:
      - rss_default
    depends_on: &depends
      - db
      - redis

    environment: &env_vars
      ROOT_ADDRESS: "https://quiz.domain.com" # Base-URL (change it)
      DB_URL: "postgresql://postgres:classquiz@db:5432/classquiz"
      REDIS: "redis://redis:6379/0?decode_responses=True"
      MAIL_ADDRESS: "email@domain.com"
      MAIL_PASSWORD: "thepass"
      MAIL_USERNAME: "email@domain.com"
      MAIL_SERVER: "mail.domain.com"
      MAX_WORKERS: "1" # Very important
      MAIL_PORT: "587"
      SECRET_KEY: "thesecretkey"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      SKIP_EMAIL_VERIFICATION: True
      HCAPTCHA_KEY: "ee81b2a1-acf3-4d20-b2a4-a7ea94c7eba5"
      MEILISEARCH_URL: "http://meilisearch:7700"
      STORAGE_BACKEND: "local"
      STORAGE_PATH: "/app/data"
      REGISTRATION_DISABLED: "True"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - rss_default
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - rss_default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "classquiz"
      POSTGRES_DB: "classquiz"
    volumes:
      - data:/var/lib/postgresql/data
  proxy:
    image: caddy:alpine
    restart: always
    networks:
      - rss_default
    volumes:
      - ./Caddyfile-docker:/etc/caddy/Caddyfile
    ports:
      - "9001:8080"
  meilisearch:
    image: getmeili/meilisearch:v0.28.0
    restart: always
    networks:
      - rss_default
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meilisearch-data:/data.ms
  worker:
    build: *build_cfg
    environment: *env_vars
    depends_on: *depends
    restart: *restart
    networks:
      - rss_default
    command: arq classquiz.worker.WorkerSettings

networks:
  rss_default:
   name: rss_default

volumes:
  data:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/quiz/data

  meilisearch-data:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/quiz/melisearchdata

```

**Comment by mawoka-myblock** [comment]
You have to set it in the frontend/Dockerfile.

**Comment by killmasta93** [comment]
oh gotcha like this? 

![image](https://github.com/mawoka-myblock/ClassQuiz/assets/13953629/983b8817-32ed-4bcf-9f46-d64fbe5119f8)

![image](https://github.com/mawoka-myblock/ClassQuiz/assets/13953629/cf0337ed-5596-4cee-85d2-4ef5b173c200)
not sure if i missed something?

**Comment by mawoka-myblock** [comment]
Looks good!

**Comment by killmasta93** [comment]
thanks for the reply, the odd issue is that after running docker-compose build i recheck and it shows the registration option still
not sure what i missed?

**Comment by mawoka-myblock** [comment]
I'll investigate further when I got some spare time.

**Comment by mawoka-myblock** [comment]
Hmmm... I checked again and it works for me. Could please try to add it into the docker-compose.yml for the frontend container as well?

**Comment by mawoka-myblock** [comment]
Maybe add it above the WORKDIR in the Dockerfile? And did you try to hard-refresh your browser with STRG + F5?

**Comment by killmasta93** [comment]
hi there so wanted to see what i could be doing wrong, as it keeps showing the register button 
![image](https://github.com/mawoka-myblock/ClassQuiz/assets/13953629/5f5d9efc-4484-4776-b7c6-6ebc0c41ce87)

this is the docker file

```
ClassQuiz# cat frontend/Dockerfile
# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

### Build Step
# pull the Node.js Docker image
FROM node:19-bullseye as builder
# ENV API_URL=http://api:80
ENV API_URL=https://mawoka.eu
#Ah, I've noticed that!!!
ENV VITE_REGISTRATION_DISABLED=True
ENV REDIS_URL=redis://localhost:6379
ENV VITE_MAPBOX_ACCESS_TOKEN=pk.eyJ1IjoibWF3b2thIiwiYSI6ImNsMjBob3d4ZjBhcGszYnE0bWp4aXB1ZW4ifQ.IByxV1qeIuEWpHCWsuB88A
# This Mapbox-token is restricted to the following urls: classquiz.de, classquiz.mawoka.eu, test.com
ENV VITE_HCAPTCHA=exxxxxx
# ENV VITE_SENTRY=https://75cb4ef1be624d8f81bbaf864b722f8a@glitch.mawoka.eu/2
#ENV VITE_GOOGLE_AUTH_ENABLED=true
#ENV VITE_GITHUB_AUTH_ENABLED=true
ENV VITE_CAPTCHA_ENABLED=true
ENV VITE_REGISTRATION_DISABLED=True
#ENV VITE_PLAUSIBLE_DATA_URL=
# change working directory
WORKDIR /usr/src/app

# copy the package.json files from local machine to the workdir in container
COPY package*.json ./
COPY pnpm-lock.yaml ./

# run npm install in our local machine
RUN corepack enable && corepack prepare pnpm@8.6.1 --activate && pnpm i

# copy the generated modules and all other files to the container
COPY . .

# build the application
RUN pnpm run build

### Serve Step
# pull the Node.js Docker image
FROM node:19-bullseye-slim

# change working directory
WORKDIR /app
COPY --from=builder /usr/src/app/package.json .
COPY --from=builder /usr/src/app/pnpm-lock.yaml .
RUN corepack enable && corepack prepare pnpm@8.6.1 --activate && pnpm i
# copy files from previous step
COPY --from=builder /usr/src/app/build .
COPY --from=builder /usr/src/app/node_modules ./node_modules

# our app is running on port 3000 within the container, so need to expose it
EXPOSE 3000

# the command that starts our app
CMD ["pnpm", "run", "run:prod"]

```

and the docker compose

```
version: "3"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - api
    networks:
      - rss_default
    environment:
      REDIS_URL: redis://redis:6379/0?decode_responses=True
      API_URL: http://api:80
  api:
    build: &build_cfg
      context: .
      dockerfile: Dockerfile
    restart: &restart always
    networks:
      - rss_default
    depends_on: &depends
      - db
      - redis

    environment: &env_vars
      ROOT_ADDRESS: "https://quiz.domain.com" # Base-URL (change it)
      DB_URL: "postgresql://postgres:classquiz@db:5432/classquiz"
      REDIS: "redis://redis:6379/0?decode_responses=True"
      MAIL_ADDRESS: "noticias@domain.com.co"
      MAIL_PASSWORD: "9xxxx"
      MAIL_USERNAME: "noticias@domain.com.co"
      MAIL_SERVER: "mail.domain.com.co"
      MAX_WORKERS: "1" # Very important
      MAIL_PORT: "587"
      SECRET_KEY: "fxxxxx"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      SKIP_EMAIL_VERIFICATION: True
      HCAPTCHA_KEY: "eexxxxxx"
      MEILISEARCH_URL: "http://meilisearch:7700"
      STORAGE_BACKEND: "local"
      STORAGE_PATH: "/app/data"
      REGISTRATION_DISABLED: "True"


  redis:
    image: redis:alpine
    restart: always
    networks:
      - rss_default
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  db:
    image: postgres:14-alpine
    restart: always
    networks:
      - rss_default
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "classquiz"
      POSTGRES_DB: "classquiz"
    volumes:
      - data:/var/lib/postgresql/data
  proxy:
    image: caddy:alpine
    restart: always
    networks:
      - rss_default
    volumes:
      - ./Caddyfile-docker:/etc/caddy/Caddyfile
    ports:
      - "9001:8080"
  meilisearch:
    image: getmeili/meilisearch:v0.28.0
    restart: always
    networks:
      - rss_default
    environment:
      MEILI_NO_ANALYTICS: true
    volumes:
      - meilisearch-data:/data.ms
  worker:
    build: *build_cfg
    environment: *env_vars
    depends_on: *depends
    restart: *restart
    networks:
      - rss_default
    command: arq classquiz.worker.WorkerSettings

networks:
  rss_default:
   name: rss_default

volumes:
  data:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/quiz/data

  meilisearch-data:
   driver: local-persist
   driver_opts:
     mountpoint: /scsi1/quiz/melisearchdata

```
after that i did a `docker-compose down -v `

then a `docker-compose build `

then a `docker-compose up -d `

i also tried deleting all containers and recreated from scratch 

Also tried accessing on another computer which never accessed the site before 

Thank you
