### ISSUE TITLE
File Upload Failure: HTTP 500 Error on /api/v1/storage Endpoint with Uppy Integration

### ISSUE THREAD

**Issue by Mergim1992** [mawoka-myblock/ClassQuiz#405]
### Which component is affected?

Media-Upload (.png)

### Did the issue occur at ClassQuiz.de, or on a self-hosted instance?

On a self-hosted instance

### How can the issue be reproduced?

Deploy the application using the provided docker-compose.yml and Nginx configuration.
Attempt to upload a file using the Uppy interface.
Observe the 500 Internal Server Error in the browser console logs.

**docker-compose.yml:**

```
# SPDX-FileCopyrightText: 2023 Marlon W (Mawoka)
#
# SPDX-License-Identifier: MPL-2.0

version: "3"

services:
  frontend:
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - redis
      - api
    environment:
      REDIS_URL: redis://redis:6379/0?decode_responses=True
      API_URL: http://api:80
  api:
    build: &build_cfg
      context: .
      dockerfile: Dockerfile
    restart: &restart always
    depends_on: &depends
      - db
      - redis

    environment: &env_vars
      # --- DON'T CHANGE FROM HERE ---
      DB_URL: "postgresql://postgres:classquiz@db:5432/classquiz" # DON'T CHANGE
      REDIS: "redis://redis:6379/0?decode_responses=True" # DON'T CHANGE
      SECRET_KEY: "10f3c7c73bdc92a8507992197c4ab73c480953a1892e79006304fadece2caf36" # Don't change it manually, use the one-liner provided in the documentation
      MAX_WORKERS: "1" # Very important and DON'T CHANGE
      ACCESS_TOKEN_EXPIRE_MINUTES: 30  # DON'T CHANGE
      MEILISEARCH_URL: "http://meilisearch:7700" # DON'T CHANGE
      # -- DON'T CHANGE TILL HERE ---

      # --- GENERAL CONFI ---
      ROOT_ADDRESS: "http://quiz.mysite.de" # CHANGE IT (without a "/" at the end)

      # --- MAIL CONFIG ---
      MAIL_PORT: "587"
      MAIL_ADDRESS: "email@email@email.email"
      MAIL_PASSWORD: "PASSWORT"
      MAIL_USERNAME: "email@email@email.email"
      MAIL_SERVER: "email@email@email.emai"
      SKIP_EMAIL_VERIFICATION: "True" # Does the user have to confirm its email by clicking a link?

      # --- EXTERNAL API CONFIG ---
      # HCAPTCHA_KEY: "HCAPTCHA_PRIVATE_KEY"
      # PIXABAY_API_KEY: "" # Get it from here: https://pixabay.com/api/docs/
      # RECAPTCHA_KEY: "" Get it from Google for the Captcha.

      # -- STORAGE CONFIG ---
      STORAGE_BACKEND: "local" # Could also be s3
      STORAGE_PATH: "/var/www/mysite/classquiz/uploads" # When s3 is used, this isn't needed.
      # If STORAGE_BACKEND is "s3"
      #S3_ACCESS_KEY: "YOUR_ACCESS_KEY"
      #S3_SECRET_KEY: "YOUR_SECRET_KEY"
      #S3_BASE_URL: "YOUR_S3_BASE_URL"

      # --- GOOGLE_AUTH ---
      #GOOGLE_CLIENT_ID: "" # Your Google-Client ID, or leave it unset if you don't want it.
      #GOOGLE_CLIENT_SECRET: "" # Your Google-Client Secret, or leave it unset if you don't want it.

      # --- GITHUB_AUTH ---
      #GITHUB_CLIENT_ID: "" # Your GitHub-Client ID, or leave it unset if you don't want it.
      #GITHUB_CLIENT_SECRET: "" # Your GitHub-Client Secret, or leave it unset if you don't want it.

      # --- Custom OpenID ---
      #CUSTOM_OPENID_PROVIDER__CLIENT_ID: "" # Adjust if needed
      #CUSTOM_OPENID_PROVIDER__CLIENT_SECRET: "" # Adjust if needed
      #CUSTOM_OPENID_PROVIDER__SERVER_METADATA_URL: "/.well-known/openid-configuration" # Adjust if needed

    volumes: # Only needed if you chose the "local" storage-backend
      - /var/www/mysite/classquiz/uploads:/var/storage

  redis:
    image: redis:alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]

  db:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "classquiz"
      POSTGRES_DB: "classquiz"
    volumes:
      - data:/var/lib/postgresql/data
  proxy:
    image: caddy:alpine
    restart: always
    volumes:
      - ./Caddyfile-docker:/etc/caddy/Caddyfile
    ports:
      - "8000:8080" # The 8000 can be changed.
  meilisearch:
    image: getmeili/meilisearch:v0.28.0
    restart: always
    environment:
      MEILI_NO_ANALYTICS: "true"
    volumes:
      - meilisearch-data:/data.ms
  worker:
    build: *build_cfg
    environment: *env_vars
    depends_on: *depends
    restart: *restart
    command: arq classquiz.worker.WorkerSettings


volumes:
  data:
  meilisearch-data:

```

quiz.mysite.de (nginx config):

```
# HTTP-Konfiguration für quiz.mysite.de
server {
    listen 80;
    listen [::]:80;
    server_name quiz.mysite.de;

    # Weiterleitung von HTTP auf HTTPS
    # If you plan to use SSL, enable the following line.
    return 301 https://$host$request_uri;

    # Proxy pass to your application on port 8000
    #location / {
    #    proxy_pass http://127.0.0.1:8000;  # Forward requests to port 8000
    #    proxy_set_header X-Real-IP $remote_addr;
    #    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    #    proxy_set_header Host $host;
    #    proxy_set_header X-Forwarded-Proto $scheme;
    #    proxy_redirect off;
    #}
}

# HTTPS-Konfiguration für quiz.mysite.de
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name quiz.mysite.de www.quiz.mysite.de;

    # Zertifikats-Dateien von Let's Encrypt
    ssl_certificate /etc/letsencrypt/live/quiz.mysite.de/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/quiz.mysite.de/privkey.pem;

    # Proxy pass to your application on port 8000
    location / {
        proxy_pass http://127.0.0.1:8000;  # Forward requests to port 8000
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_redirect off;

        # CORS-Header hinzufügen
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range' always;
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range' always;
    }

    location ~ /\.ht {
        deny all;
    }
}
```

### Describe the bug (with screenshots if possible)

While attempting to upload files via the /api/v1/storage endpoint using Uppy in a Dockerized environment, the server returns a 500 Internal Server Error. The backend is running in a containerized setup with Nginx as the proxy, and file storage is configured using the local storage backend. The issue persists despite adding necessary CORS headers in the Nginx configuration.

**This is the web-console error I receive when upload a picture:**
```

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  630ms]

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  711ms]

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  608ms]

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  577ms]

POST
    https://quiz.mysite/api/v1/storage/
Status
500
VersionHTTP/2
Übertragen185 B (21 B Größe)
Referrer Policystrict-origin-when-cross-origin
DNS-AuflösungSystem

[Uppy] [17:11:51] Upload error loggers.js:13:19
    error loggers.js:13
    log Uppy.js:1128
    vh Uppy.js:1476
    r index.js:131
    emit index.js:33
    emit Uppy.js:312
    <anonym> index.js:230
    i index.js:348
    o RateLimitedQueue.js:148
    tp RateLimitedQueue.js:231
    run RateLimitedQueue.js:113
    l RateLimitedQueue.js:144
    wrapPromiseFunction RateLimitedQueue.js:143
    gp index.js:364
    bp index.js:447
    bp index.js:428
    value index.js:149
    _h Uppy.js:1726
    upload Uppy.js:1240
    (Async: promise callback)
    upload Uppy.js:1225
    startUpload StatusBar.js:99
    Preact 27
    <anonym> UIPlugin.js:101
    e UIPlugin.js:27
    (Async: promise callback)
    Ah UIPlugin.js:21
    update UIPlugin.js:151
XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  1805ms]

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  1248ms]

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  635ms]

XHRPOST
https://quiz.mysite/api/v1/storage/
[HTTP/2 500  580ms]

[Uppy] [17:14:59] Upload error loggers.js:13:19

```

### Device

Desktop

### Operating System

Linux Ubuntu 24.04

### Browser

Safari, Firefox
